import { jsPDF } from "jspdf";

export const addStandardLetterhead = (doc: jsPDF, title: string) => {
  const width = doc.internal.pageSize.getWidth();
  
  // Header background
  doc.setFillColor(8, 90, 78); // Superior Teal
  doc.rect(0, 0, width, 60, "F");
  
  // Header text
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("SUPERIOR GROUP OF COLLEGES", width / 2, 25, { align: "center" });
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Jahanian Campus - Empowering Success", width / 2, 40, { align: "center" });
  
  // Title
  doc.setTextColor(255, 204, 0); // Superior gold
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title.toUpperCase(), width / 2, 53, { align: "center" });
  
  // Footer
  const baseHeight = doc.internal.pageSize.getHeight();
  doc.setFillColor(8, 90, 78);
  doc.rect(0, baseHeight - 30, width, 30, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by SGC-J Management System", width / 2, baseHeight - 15, { align: "center" });
  doc.text(new Date().toLocaleDateString(), width - 30, baseHeight - 15, { align: "right" });
  
  // Reset colors for body
  doc.setTextColor(0, 0, 0);
  doc.setFillColor(255, 255, 255);
};
